name: backend CI

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum

      - name: check Go formatting
        working-directory: ./backend
        run: |
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
            echo "The following files are not formatted:"
            echo "$unformatted"
            echo "Please run 'gofmt -w .' to format your code"
            exit 1
          fi

      - name: download dependencies
        working-directory: ./backend
        run: go mod download

      - name: run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          working-directory: ./backend

      - name: run tests with race detector
        working-directory: ./backend
        run: go test -race -v ./...
