name: frontend CI

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true # cancel existing runs if PR has been updated -- cost savings

jobs:
  ci_pipeline:
    name: "CI Pipeline"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version-file: "./frontend/.nvmrc"
      - name: Install Dependencies
        working-directory: frontend
        run: npm ci

      - name: Format
        working-directory: frontend
        run: npm run format

      - name: Lint
        working-directory: frontend
        run: npm run lint

      - name: Build for production
        working-directory: frontend
        run: npm run build
